name: Cortex
description: Cortex - The Ultimate AI-Powered Content, Image and Code Creation Tool with Flutter.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Commons
  nb_utils: ^7.0.7
  google_fonts: ^6.2.1
  #html: ^0.15.5
  intl: ^0.19.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.2.6
  flutter_vector_icons: ^2.0.0
  lottie: ^3.1.3
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  stream_transform: ^2.1.0
  flutter_local_notifications: ^18.0.1
  slider_button: ^2.1.0
  carousel_slider: ^5.0.0
  flutter_spinkit: ^5.2.1
  rive: ^0.13.17
  record: ^5.2.0
  share_plus: ^10.1.2
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2
  flutter_html: ^3.0.0-alpha.6
  group_button: ^5.3.4
  flutter_markdown: ^0.7.4+1
  syncfusion_flutter_pdf: ^27.1.56

  #Network
  dio: ^5.7.0

  #firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_crashlytics: ^4.1.3
  firebase_messaging: ^15.1.3
  firebase_remote_config: 5.1.3
  firebase_core_web: ^2.18.1


  # SOCIAL LOGIN

  the_apple_sign_in: ^1.1.1
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12

  # State Management
  get: ^4.6.6

  #Storage
  get_storage: ^2.1.1

  #PhotoViewGallery
  photo_view: ^0.15.0
  before_after: ^3.1.0

  #Pickers
  file_picker: ^8.1.3
  image_picker: ^1.1.2
  country_picker: ^2.0.26

  # Google Map
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0

  # Payment
  purchases_flutter: ^6.30.0
  flutter_stripe: ^11.2.0
  razorpay_flutter: ^1.3.7
  flutterwave_standard:
    git:
      url: https://github.com/iqonic-design/flutterwave_standard.git
      ref: main
  flutter_paypal_checkout:
    git:
      url: https://github.com/iqonic-design/flutter_paypal_checkout.git
      ref: main

  flutter_paystack:
    git:
      url: https://github.com/iqonic-design/flutter_paystack.git
      ref: 1.1.0

  midpay:
    git:
      url: https://github.com/iqonic-design/midpay.git
      ref: main
  cinetpay:
    git:
      url: https://github.com/iqonic-design/cinetpay.git
      ref: main
  # Google
  google_mobile_ads: ^5.2.0
  js: ^0.7.1

  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/flags/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/icons/navigation/
    - assets/rive/

  fonts:
    - family: Archia
      fonts:
        - asset: assets/fonts/Archia-Regular.otf
